### ISSUE TITLE
string and cursor pending unit tests

### ISSUE THREAD

**Issue by marinofelipe** [marinofelipe/UICurrencyTextField#1]
## What problems I want to solve?
unit tests for non tested string extension funcs and cursor positioning

## Tasks
- [x] String extension tests
   - [x] adding decimal separators to String
   - [x] removing currency separator
   - [x] represents zero
- [x] CurrencyTextField
   - [x] autoclear
   - [x] cursor positioning
## Dependecies / References
No dependencies and/or references by now.

**Comment by marinofelipe** [comment]
done in #16
