### ISSUE TITLE
Contribution MD + readme improvement

### ISSUE THREAD

**Issue by marinofelipe** [marinofelipe/UICurrencyTextField#21]
## What problems I want to solve?
The repo does not have a contribution guideline file and the readme could be better.

## Tasks
- [ ] Define and create contributing.md
- [ ] Define and create pull_request.md
- [ ] Improve readme.md

## Dependecies / References
...
